### ISSUE TITLE
Use product schema from oms package

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/available-to-promise#152]
## What is the motivation for adding/enhancing this feature?

As we have defined product specific api calls and product schema in oms package and thus need to use the package to perform product specific operations

## What are the acceptance criteria?

- [ ] Use oms api to fetch product information
- [ ] Make use of types in product module

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

## Additional information

Follow [here](https://github.com/hotwax/oms-api#usage) to setup oms api package

Reference: https://github.com/hotwax/import/pull/47

**Comment by Dhiraj1405** [comment]
Closing this as its a future project, will create new ticket when required.
