### ISSUE TITLE
Define state for maintaining current job information

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/available-to-promise#168]
## Current behavior
 
Currently, when opening job configuration component we are passing job information in props and not maintaining the state for the current job, due to which we need to handle multiple scenarios separately.

 ## Expected behavior
 
We need a current state that will store the information for current job being displayed in the and thus we can simply maintain and handle the operations on current job

 ## Steps to reproduce the issue
 

 ## Can you handle fixing this bug by yourself?

 - [x] YES
 - [ ] NO

 ## Environment details
 
 - Browser: 
 - OS: 
 - Code Version: 

 ## Additional information
 
 - [ ] Issue https://github.com/hotwax/job-manager/issues/382

**Comment by amansinghbais** [comment]
The whole flow of the application is updated in the release 3.0.0. And hence this ticket is not relevant now. Hence closing this.
