### ISSUE TITLE
Available to Promise backend implementation

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/available-to-promise#242]
## What is the motivation for adding/enhancing this feature?
The Available to Promise feature expands upon the current threshold setting capabilities offered by the threshold app. Users can now set thresholds, safety stock levels, and allow pickup and brokering directly from the app. These settings can be configured based on various filter criteria, including tags and product features.

## What are the acceptance criteria?
1) Data modeling for rules, conditions, actions etc.
2) APIs for CRUD operations on rules.
3) Rule execution logic using drools for setting up, threshold, safety stocks, allow pickup and allow brokering.
4) Schedule for execution.
5) Cleanup of old jobs.

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
UI - https://www.figma.com/file/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?type=design&node-id=34317-190810&mode=design&t=PJEG8PVsaBSlWqs6-0

**Comment by dt2patel** [comment]
Closing issue, implementation done
