### ISSUE TITLE
Use i18n from the dxp-components

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/available-to-promise#259]
## What is the motivation for adding/enhancing this feature?

Currently our app uses i18n from the app only, but we need to use it from the dxp-components.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified for English locale and found that it is working fine. Hence, closing this ticket.
