### ISSUE TITLE
Favorite Product Store Setting and Visibility

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/available-to-promise#293]
## Description

1. Feature Description:

Current State: Users do not have the ability to set a favorite product store.
Proposed Feature: Add support allowing users to designate a favorite product store.

2. Visibility in Menu Footer:

Current State: Upon app login, users cannot immediately see their favorite product store.
Proposed Change: Display the favorite product store prominently in the menu footer upon user login.

**Comment by Dhiraj1405** [comment]
Not required. Hence closing
