### ISSUE TITLE
Incorrect Search Results for Product Tags and Features

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/available-to-promise#295]
## Note
Currently, user is not able to search the product features by the color name.

## Expected behavior
The search results should accurately match the entered product tags or features, providing users with relevant product listings.

## Steps to reproduce the issue
Login the app with valid user credentials.
Open either threshold/store pickup/safety stock/shipping.
Navigate to the search bar of product tags/features of any rule.
Enter product tags or features in the search bar and press enter.
Observe the search results displayed.

 ## Environment details
 App version : THRESHOLD-2.0-70DCF78
 App environment : DEV

 ## Additional information
 https://jam.dev/c/07b19840-7351-49e3-94bf-01bc6566a2b7

**Comment by amansinghbais** [comment]
Will be handled in following issue: https://github.com/hotwax/available-to-promise/issues/360

**Comment by ravilodhi** [comment]
This is handled under #360
