### ISSUE TITLE
Show chips for all selected product filters in the Product Filters modal

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/available-to-promise#304]
## What is the motivation for adding/enhancing this feature?

Currently in the product filters modal, we fetch filters on searching and we have clear all button which clear all the filters even if they are in fetch list or not. This creates confusion.

Hence show all the selected product filters in the chip even if the filter are not present in the modal.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.1.0. Hence, closing this ticket.
