### ISSUE TITLE
Preserve Formatting of Group Descriptions in Cards

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/available-to-promise#334]
## Description
Preserve the formatting of descriptions in rule and group cards to ensure that multiline descriptions are displayed in the same format as they are saved. This enhances readability and consistency across the application.

## Additional information
https://jam.dev/c/54328fc7-0d58-4129-b80d-218d2eeeaae4

**Comment by ymaheshwari1** [comment]
Refer order routing description feature where we are preserving the group description.

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.1.0. Hence, closing this ticket.
https://jam.dev/c/d4d5d38a-a1eb-4a52-b99d-170fd5bbbe30
