### ISSUE TITLE
Issue with Duplicate Modals Opening on Rapid Clicking of Edit/Add Buttons

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/available-to-promise#335]
## Expected behavior
The modal should open only once when the edit/add button is clicked, regardless of the speed of clicking or hitting the enter key.

## Steps to reproduce the issue
Click rapidly on the edit/add button of facilities/channels/tags/features/rules/groups.
Hit the enter key immediately after clicking the edit/add button.
Observe that the modal opens twice.

 ## Environment details
 App version : THRESHOLD-2.0-2C00FE9
 App environment : DEV
 
 ## Additional information
 https://jam.dev/c/03017939-e514-4ffa-b093-21b6adf172f5

**Comment by amansinghbais** [comment]
@Adameddy26 
Following issue should be occuring in across all the apps. This issue is not app specific and hence should be tested across all the apps and create issues accordingly.

**Comment by ymaheshwari1** [comment]
> [@Adameddy26](https://github.com/Adameddy26) Following issue should be occuring in across all the apps. This issue is not app specific and hence should be tested across all the apps and create issues accordingly.

@Adameddy26 Please check on this and create issue in Dxp if applicable to all apps

**Comment by Dhiraj1405** [comment]
Will recreate when users raises this issue.
