### ISSUE TITLE
Add support for selecting all facilities for a rule

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/available-to-promise#347]
## What is the motivation for adding/enhancing this feature?

Currently user needs to select all the facilities or facility groups for applying atp, Here we need to give user a option to select all the facilities to apply atp rule to.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in latest release. Hence, closing it.
