### ISSUE TITLE
Unable to Toggle Store Pickup Button for Facilities in Facilities Section

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/available-to-promise#355]
## Expected behavior
The toggle button should respond to user interaction, allowing the user to enable or disable the store pickup option for the selected facility.

 ## Current behavior
The toggle button does not respond to user interaction, remaining in its initial state and preventing any changes to the store pickup setting for the facility.

 ## Steps to reproduce the issue
Navigate to the facilities section of the store pickup module.
Attempt to click the toggle button for any listed facility to turn on or off the store pickup option.

 ## Environment details
 App version :  V3.0.2
 App environment : PROD

 ## Additional information
![Screenshot from 2024-06-27 16-47-35](https://github.com/hotwax/available-to-promise/assets/158989293/bca6c97b-3276-484c-8990-9a2239bdbc83)

**Comment by ymaheshwari1** [comment]
@amansinghbais Check on this and if there is any dependency, then add the same on the issue.

**Comment by Dhiraj1405** [comment]
Dependency on Moqui component.

**Comment by amansinghbais** [comment]
After a discussion with the Moqui team, it has been confirmed that the issue will be resolved on their side, requiring no changes on the app side.

According to the updates provided, the following has been fixed. And hence marking this ticket to Dev-Complete status for testing.

**Comment by Adameddy26** [comment]
Issue verified and working fine in version v3.2.0. Hence, closing this ticket.
