### ISSUE TITLE
Add functionality to the Publish segment of the inventory channels page

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/available-to-promise#356]
## What is the motivation for adding/enhancing this feature?

Make the Publish segment of the inventory channels page functional for allowing user to setup jobs.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.1.0. Hence, closing this ticket.
