### ISSUE TITLE
Feature search is not consistent

### ISSUE THREAD

**Issue by dt2patel** [hotwax/available-to-promise#360]
## Current behavior
 
Feature search and sometimes take search doesn't feel consistent. We need to add a spinner to show search is happening as well as also show a default list of features so that user feels like there is at least some content.

https://jam.dev/c/6aed993e-a5a9-4e11-b1d4-bb14c8063e47

Tried searching for black clothes but no keyword was working

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v3.1.0. Hence, closing this ticket.
https://jam.dev/c/82a275a6-d38d-4c3d-a467-c47a0533f0d7
