### ISSUE TITLE
Improve rule template generation logic for backend compatibility

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/available-to-promise#363]
## What is the motivation for adding/enhancing this feature?

Earlier we were using the multiValued property while rule generation, but now the multiValued property is removed from the backend. And hence need to make necessary change for proper rule template generation.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.1.0. Hence, closing this ticket.
