### ISSUE TITLE
Handle solrFacets API response as per the updated api response

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/available-to-promise#369]
## What is the motivation for adding/enhancing this feature?
Handle solrFacets API response as per the updated api response.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ravilodhi** [comment]
@Adameddy26 If features and tags search is working correctly then we can close this issue.

**Comment by Adameddy26** [comment]
Verified and working fine in release v3.2.0. Hence, closing this ticket.
