### ISSUE TITLE
Inventory channel UI label

### ISSUE THREAD

**Issue by dt2patel** [hotwax/available-to-promise#384]
## Current behavior
 
On the publish inventory page, the term "inventory group" is used, it should say "inventory channel"

![Screenshot 2024-10-26 at 2 52 21 PM](https://github.com/user-attachments/assets/94896af2-969f-4d24-acd8-9641a9ae1dca)

**Comment by Adameddy26** [comment]
Assigning this ticket to @priyanshee1604 for verification.
CC : @dt2patel
