### ISSUE TITLE
Add option to view archived rules

### ISSUE THREAD

**Issue by dt2patel** [hotwax/available-to-promise#386]
## What is the motivation for adding/enhancing this feature?

![Screenshot 2024-11-09 at 8 01 31 AM](https://github.com/user-attachments/assets/c4589c41-686e-4dcc-9bf7-1e7839747e43)
Works the same as the routing app which opens a modal with options to unarchive

**Comment by Adameddy26** [comment]
Verified the changes in release v3.3.0 and are working fine. Hence, closing this ticket..
